DROP DATABASE IF EXISTS team1;
CREATE DATABASE IF NOT EXISTS team1;
USE team1;

DROP TABLE IF EXISTS address;
CREATE TABLE IF NOT EXISTS address (

	address_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	street_no INTEGER,
	street_name VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	state VARCHAR(20),
	country VARCHAR(50) NOT NULL,
	zip VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user (

	username VARCHAR(30) PRIMARY KEY,
	password VARCHAR(64) NOT NULL,
	email VARCHAR(255) NOT NULL,
	is_admin BOOLEAN NOT NULL,
	first_name VARCHAR(35) NOT NULL,
	last_name VARCHAR(35) NOT NULL,
	address_id INTEGER NOT NULL,
	age INTEGER NOT NULL,
	suspended BOOLEAN NOT NULL,

	FOREIGN KEY (address_id) REFERENCES address(address_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

